CREATE TABLE IF NOT EXISTS "leads" (
	"id" text PRIMARY KEY NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now(),
	"event_name" text,
	"event_start_date" timestamp,
	"event_end_date" timestamp,
	"first_name" text,
	"last_name" text,
	"job_title" text,
	"company" text,
	"website" text,
	"email" text,
	"linkedin" text,
	"has_business_card" boolean DEFAULT false,
	"has_text_note" boolean DEFAULT false,
	"has_voice_memo" boolean DEFAULT false,
	"main_interest" text,
	"next_steps" text,
	"notes" text,
	"company_industry" text,
	"company_size" text,
	"company_business" text,
	"referral" boolean DEFAULT false,
	"is_target" boolean DEFAULT false,
	"icp_fit" boolean,
	"qualification_reason" text,
	"processing_status" text DEFAULT 'pending',
	"enrichment_status" text DEFAULT 'pending',
	"contact_timing" text,
	"contact_date" text,
	"follow_up_template" text,
	"raw_business_card" text,
	"raw_text_note" text,
	"raw_voice_memo" text
);
